replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
gitlab:
  app:
  env:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: https://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 5000
  internalPort: 5000
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
livenessProbe:
  path: "/_heartbeat"
  initialDelaySeconds: 10
  timeoutSeconds: 10
  scheme: "HTTP"
readinessProbe:
  path: "/_heartbeat"
  initialDelaySeconds: 10
  timeoutSeconds: 10
  scheme: "HTTP"
postgresql:
  enabled: false
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
