include:
  - template: Auto-DevOps.gitlab-ci.yml

.auto-deploy:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.12.0"

build:
  stage: build
  before_script:
    - echo $CI_BUILD_REF_NAME > BRANCH
    - echo $CI_COMMIT_SHA > COMMIT

review:
  stage: review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_NAME.$KUBE_INGRESS_BASE_DOMAIN

staging:
  stage: staging
  environment:
    name: staging
    url: http://$KUBE_INGRESS_BASE_DOMAIN

production:
  stage: production
  environment:
    name: production
    url: http://$KUBE_INGRESS_BASE_DOMAIN

production_manual:
  stage: production
  environment:
    name: production
    url: http://$KUBE_INGRESS_BASE_DOMAIN
