version: '3'
services:
  app:
    build: .
    image: hermes-app
    ports:
      - "3000"
    labels:
      traefik.frontend.rule: "Host:hermes.docker.localhost"
    volumes:
      - "./:/app"
    environment:
      LANG: "en_US.UTF-8"
      RAILS_SERVE_STATIC_FILES: enabled
      RAILS_LOG_TO_STDOUT: enabled
    depends_on:
      - db
      - net
  db:
    image: postgres:10.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata
  net:
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pgdata:
