version: '3'
services:
  app:
    build: .
    image: hermes-app
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    environment:
      LANG: "en_US.UTF-8"
      RAILS_SERVE_STATIC_FILES: enabled
      RAILS_LOG_TO_STDOUT: enabled
    depends_on:
      - db
  db:
    image: postgres:10.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
