version: "3.7"

x-shared-environment-variables: &shared-environment-variables
  RAILS_ENV: development
  GITLAB_ENVIRONMENT_NAME: development
  GITLAB_ENVIRONMENT_URL: https://hermes.mythcoders.dev
  REDIS_URL: redis://myth-redis:6379/0
  REDIS_NAMESPACE: hermes-dev
  REDIS_WORKER_NAMESPACE: hermes-worker-dev

services:
  app:
    image: hermes
    build:
      context: .
      target: base
    container_name: hermes-app
    command: ["sh", "./scripts/app", "start", "setup"]
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:hermes.mythcoders.dev"
    volumes:
      - "./:/app"
    environment:
      <<: *shared-environment-variables
    stdin_open: true
    tty: true

  worker:
    image: hermes
    container_name: hermes-worker
    command: ["sh", "./scripts/worker", "start"]
    volumes:
      - .:/app
    environment:
      <<: *shared-environment-variables
    depends_on:
      - app

networks:
  default:
    name: mythcoders_dev
    external: true
