version: "3.7"

x-shared-environment-variables: &shared-environment-variables
  RAILS_ENV: development
  NODE_ENV: development

services:
  app:
    image: hermes
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: hermes-app
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    expose:
      - "3000"
    volumes:
      - .:/rails
    environment:
      <<: *shared-environment-variables
    stdin_open: true
    tty: true

  # css:
  #   image: hermes
  #   container_name: hermes-css
  #   command: ["sh", "./scripts/css"]
  #   volumes:
  #     - .:/rails
  #   environment:
  #     <<: *shared-environment-variables
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - app

  web:
    image: nginx:latest
    container_name: hermes-web
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf
      - ./dev/mythcoders.test.crt:/ssl/mythcoders.test.crt
      - ./dev/mythcoders.test.key:/ssl/mythcoders.test.key
      - ./log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
