version: '3'
services:
  app:
    build: .
    image: hermes-app
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    ports:
      - "3000"
    labels:
      traefik.frontend.rule: "Host:hermes.docker.localhost"
    volumes:
      - "./:/app"
    environment:
      LANG: "en_US.UTF-8"
      RAILS_SERVE_STATIC_FILES: enabled
      RAILS_LOG_TO_STDOUT: enabled
    depends_on:
      - net
  net:
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pgdata:
