version: "3.7"

x-shared-environment-variables: &shared-environment-variables
  GITLAB_ENVIRONMENT_NAME: development
  ENVIRONMENT_URL: https://hermes.mythcoders.dev
  NODE_ENV: development
  RAILS_ENV: development
  REDIS_NAMESPACE: hermes-dev
  REDIS_URL: redis://myth-redis:6379/0
  REDIS_WORKER_NAMESPACE: hermes-worker-dev
  SES_CONFIGSET: Hermes-Dev
  STORAGE_BUCKET: mcdig-dvstg-com1

services:
  app:
    image: hermes
    build:
      context: .
      target: base
    container_name: hermes-app
    command: ["sh", "./scripts/app", "start", "setup"]
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:hermes.mythcoders.dev"
    volumes:
      - .:/opt/hermes
    environment:
      <<: *shared-environment-variables
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - webpacker
    stdin_open: true
    tty: true

  worker:
    image: hermes
    container_name: hermes-worker
    command: ["sh", "./scripts/worker", "start"]
    volumes:
      - .:/opt/hermes
    environment:
      <<: *shared-environment-variables
    depends_on:
      - app

  webpacker:
    image: hermes
    container_name: hermes-webpacker
    command: ["sh", "./scripts/webpack"]
    environment:
      <<: *shared-environment-variables
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/opt/hermes

networks:
  default:
    name: mythcoders_dev
    external: true
