default: &defaults
  push_api_key: "<%= Rails.application.credentials.dig(:appsignal_key) %>"
  name: "Hermes"
  running_in_container: true
  ignore_actions:
    - "GET /_ping"
    - "GET /_heartbeat"


  # Actions that should not be monitored by AppSignal
  # ignore_actions:
  #   - ApplicationController#isup

  # Errors that should not be recorded by AppSignal
  # For more information see our docs:
  # https://docs.appsignal.com/ruby/configuration/ignore-errors.html
  # ignore_errors:
  #   - Exception
  #   - NoMemoryError
  #   - ScriptError
  #   - LoadError
  #   - NotImplementedError
  #   - SyntaxError
  #   - SecurityError
  #   - SignalException
  #   - Interrupt
  #   - SystemExit
  #   - SystemStackError

  # See http://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
development:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true

review:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: true
