#!/bin/bash

echo '==> Booting Hermes...'

if [ "$2" == "setup" ]; then
  echo "==> Verifying database..."
  ./bin/rails db:exists && ./bin/rails db:migrate VERBOSE=true || ./bin/rails db:setup VERBOSE=true
fi

if [ "$1" == "start" ]; then
  if [ -f "${APP_HOME}/tmp/pids/server.pid" ]; then
    echo "==> Flushing server.pid"
    rm -rf ${APP_HOME}/tmp/health_checks/app
    rm -rf ${APP_HOME}/tmp/pids/server.pid
  fi

  echo "==> Launching web server..."
  mkdir -p ${APP_HOME}/tmp/health_checks && touch ${APP_HOME}/tmp/health_checks/app
  ./bin/rails s -b 0.0.0.0 -p 5000
fi
