name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ github.actor }}:${{ secrets.PACKAGE_TOKEN }}
        with:
          bundler-cache: true

      - name: standardrb
        run: ./scripts/cibuild linter

      - name: brakeman
        continue-on-error: true
        run: |
          gem install brakeman
          ./scripts/cibuild brakeman

      - name: bundler audit
        run: |
          gem install bundler-audit
          ./scripts/cibuild audit
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://hermes:hermes@localhost:5432/hermes_test
      ELASTIC_APM_ENABLED: false
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      REDIS_URL: redis://localhost:6379/0
      STORAGE_BUCKET: mcdig-rvstg-com1
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: hermes
          POSTGRES_PASSWORD: hermes
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ github.actor }}:${{ secrets.PACKAGE_TOKEN }}
        with:
          bundler-cache: true

      # - name: precompile assets
      #   run: |
      #     ELASTIC_APM_ENABLED=false ASSETS_PRECOMPILE=1 SECRET_KEY_BASE=1 \
      #     RAILS_ENV=test bundle exec rake assets:precompile

      - name: setup database
        run: ./bin/rails db:setup

      - name: rspec
        run: ./scripts/cibuild rspec
